### Criar pessoa
POST http://0.0.0.0:3000/pessoas
Content-Type: application/json

{
  "nome": "nome",
  "apelido": "nick",
  "nascimento": "2023-10-01",
  "stack": [
    "go",
    "rust"
  ]
}

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Buscar pessoas por id
GET http://0.0.0.0:3000/pessoas/018aed86-d639-722c-9127-e0e455930e82

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Buscar pessoas
GET http://0.0.0.0:3000/pessoas

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}

### Contar pessoas
GET http://0.0.0.0:3000/contagem-pessoa

> {%
    client.test("Request executed successfully", function () {
        client.assert(response.status === 200, "Response status is not 200");
    });
%}
